site_name: Python-100-Days
site_description: Python - 100天从新手到大师
site_author: OpenPowers
site_url: https://github.com/OpenPowers

repo_name: 'OpenPowers/Python-100-Days'
repo_url: 'https://github.com/OpenPowers/Python-100-Days'

theme:
  name: material
  logo: assets/python-logo@2x.png # 徽标
  favicon: assets/favicon.png # 网站图标
  icon: # 与repo_name一起使用
    repo: fontawesome/brands/github # 使用GitHub图标
  palette:
    - scheme: default # 日间模式
      primary: 'Blue Grey' # 上方的
      accent: Pink # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    # primary: 'Blue Grey'
    # accent: 'Pink'
  features:
    - navigation.instant # 启用即时加载
    - navigation.expand # 不折叠左侧nav节点
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    # - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky # 固定（浏览时不收起）标签
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.highlight # 搜索出的文章关键词加入高亮
    - tabs: false
    - search.suggest # 搜索输入一些字母时推荐补全整个单词,即右箭头自动补全
    - navigation.sections # nav节点缩进
    - navigation.indexes # 指定节点index pages ，跟instant不兼容

    - header.autohide # 顶部下滑时自动隐藏
    - search.share # 搜索分享
    - toc.follow # 启用目录的锚点跟随，侧边栏会自动滚动，以便活动锚点始终可见
    # - toc.integrate # 关闭右侧目录

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  language: 'zh'

plugins:
  - search # 内置的搜索插件
  # - tags # 内置的标签插件
  - git-revision-date-localized: # 在每个页面底部添加最后更新日期和创建文档的支持
      enable_creation_date: true
  # - git-authors

copyright: Copyright &copy; 2024 OpenPowers # 左下角的版权声明

extra:
  homepage: https://docs.python.org/zh-cn/3/ # 徽标链接到文档的主页
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  version:
    provider: mike # 版本控制
    default: latest
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/github
      link: https://github.com/OpenPowers
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<openpowers@outlook.com> #联系方式
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性以及用户是否找到他们正在搜索的内容。在您同意的情况下，您正在帮助我们改进文档。

markdown_extensions:
  - meta # 支持markdown博客文件头的元数据，比如标题
  - abbr # 添加了向元素添加小工具提示的功能
  - md_in_html # 允许在 HTML 中编写 Markdown
  - toc: # 锚点
      permalink: true # 在每个标题的末尾添加一个包含段落符号或其他自定义符号的锚链接
      toc_depth: 6
  - footnotes # 支持脚注
  - admonition  # 支持提示块
  - pymdownx.details  # 提示块可折叠
  - attr_list # 属性列表扩展允许使用特殊语法将 HTML 属性和 CSS 类添加到几乎每个Markdown 内联和块级元素。
  - def_list # 定义列表扩展添加了通过 Markdown 向文档添加定义列表（在 HTML 中通常称为描述列表）的功能。
  - pymdownx.arithmatex # latex支持
  # - pymdownx.betterem: # 对加粗和斜体更好的检测
      # smart_enable: all
  - pymdownx.caret # 下划线上标
  - pymdownx.mark # 文本高亮
  - pymdownx.critic # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.tilde # 删除线下标
  # - pymdownx.emoji: # 表情
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
  #     #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.magiclink # 自动识别超链接
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.snippets # 添加了使用简单语法将任意文件中的内容嵌入文档（包括其他文档或源文件）的功能
  - tables # 表格
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true

  - pymdownx.inlinehilite # 支持行内语法高亮
  # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
  - pymdownx.highlight:
      css_class: highlight
      guess_lang: false
      noclasses: true
      pygments_style: xcode
      anchor_linenums: true # 如果代码块包含行号，启用此设置将用锚链接包​​裹它们，因此可以更轻松地进行超链接和共享
      use_pygments: true # 是否应在构建期间使用Pygments或在浏览器中使用 JavaScript 语法高亮器执行突出显示
      auto_title: true # 显示正在使用的语言的名称
      linenums: true # 显示行号
      linenums_style: table
  - pymdownx.superfences # 允许任意嵌套代码和内容块，包括警告、选项卡、列表和所有其他元素，和codehilite插件冲突

  - pymdownx.keys # 添加了一个简单的语法以允许呈现键盘键和组合
  - pymdownx.tabbed: # Tabbed扩展允许使用内容选项卡，这是一种将相关内容和代码块分组到可访问选项卡下的简单方法
      alternate_style: true
  # - codehilite: # 代码块高亮插件，被Highlight取代
  #     guess_lang: false
  #     css_class: highlight
  #     linenums: true # 显示行号
  #     pygments_style: tango
  #     noclasses: true
  #     use_pygments: true # 是否使用 Pygments 库进行代码高亮，默认为 True

# 自定义css
extra_css:
  - stylesheets/custom.css

# 自定义js
extra_javascript:
  - javascripts/custom.js

nav:
  - index:
    - index: index.md
  - Day01-15:
    - 01.初识Python: Day01-15/01.初识Python.md
    - 02.语言元素: Day01-15/02.语言元素.md
    - 03.分支结构: Day01-15/03.分支结构.md
    - 04.循环结构: Day01-15/04.循环结构.md
    - 05.构造程序逻辑: Day01-15/05.构造程序逻辑.md
    - 06.函数和模块的使用: Day01-15/06.函数和模块的使用.md
    - 07.字符串和常用数据结构: Day01-15/07.字符串和常用数据结构.md
    - 08.面向对象编程基础: Day01-15/08.面向对象编程基础.md
    - 09.面向对象进阶: Day01-15/09.面向对象进阶.md
    - 10.图形用户界面和游戏开发: Day01-15/10.图形用户界面和游戏开发.md
    - 11.文件和异常: Day01-15/11.文件和异常.md
    - 12.字符串和正则表达式: Day01-15/12.字符串和正则表达式.md
    - 13.进程和线程: Day01-15/13.进程和线程.md
    - 14.网络编程入门和网络应用开发: Day01-15/14.网络编程入门和网络应用开发.md
    - 15.图像和办公文档处理: Day01-15/15.图像和办公文档处理.md
  - Day16-20:
    - 16-20.Python语言进阶: Day16-20/16-20.Python语言进阶.md
  - Day21-30:
    - 21-30.Web前端概述: Day21-30/21-30.Web前端概述.md
  - Day31-35:
    - 31-35.玩转Linux操作系统: Day31-35/31-35.玩转Linux操作系统.md
  - Day36-45:
    - 36.关系型数据库和MySQL概述: Day36-45/36.关系型数据库和MySQL概述.md
    - 37.SQL详解之DDL: Day36-45/37.SQL详解之DDL.md
    - 38.SQL详解之DML: Day36-45/38.SQL详解之DML.md
    - 39.SQL详解之DQL: Day36-45/39.SQL详解之DQL.md
    - 40.SQL详解之DCL: Day36-45/40.SQL详解之DCL.md
    - 41.MySQL新特性: Day36-45/41.MySQL新特性.md
    - 42.视图、函数和过程: Day36-45/42.视图、函数和过程.md
    - 43.索引: Day36-45/43.索引.md
    - 44.Python接入MySQL数据库: Day36-45/44.Python接入MySQL数据库.md
    - 45.大数据平台和HiveSQL: Day36-45/45.大数据平台和HiveSQL.md
  - Day46-60:
    - 46.Django快速上手: Day46-60/46.Django快速上手.md
    - 47.深入模型: Day46-60/47.深入模型.md
    - 48.静态资源和Ajax请求: Day46-60/48.静态资源和Ajax请求.md
    - 49.Cookie和Session: Day46-60/49.Cookie和Session.md
    - 50.制作报表: Day46-60/50.制作报表.md
    - 51.日志和调试工具栏: Day46-60/51.日志和调试工具栏.md
    - 52.中间件的应用: Day46-60/52.中间件的应用.md
    - 53.前后端分离开发入门: Day46-60/53.前后端分离开发入门.md
    - 54.RESTful架构和DRF入门: Day46-60/54.RESTful架构和DRF入门.md
    - 55.RESTful架构和DRF进阶: Day46-60/55.RESTful架构和DRF进阶.md
    - 56.使用缓存: Day46-60/56.使用缓存.md
    - 57.接入三方平台: Day46-60/57.接入三方平台.md
    - 58.异步任务和定时任务: Day46-60/58.异步任务和定时任务.md
    - 59.单元测试: Day46-60/59.单元测试.md
    - 60.项目上线: Day46-60/60.项目上线.md
  - Day61-65:
    - 61.网络数据采集概述: Day61-65/61.网络数据采集概述.md
    - 62.用Python获取网络资源-1: Day61-65/62.用Python获取网络资源-1.md
    - 62.用Python解析HTML页面-2: Day61-65/62.用Python解析HTML页面-2.md
    - 63.Python中的并发编程-1: Day61-65/63.Python中的并发编程-1.md
    - 63.Python中的并发编程-2: Day61-65/63.Python中的并发编程-2.md
    - 63.Python中的并发编程-3: Day61-65/63.Python中的并发编程-3.md
    - 63.并发编程在爬虫中的应用: Day61-65/63.并发编程在爬虫中的应用.md
    - 64.使用Selenium抓取网页动态内容: Day61-65/64.使用Selenium抓取网页动态内容.md
    - 65.爬虫框架Scrapy简介: Day61-65/65.爬虫框架Scrapy简介.md
  - Day66-80:
    - 66.数据分析概述: Day66-80/66.数据分析概述.md
    - 67.环境准备: Day66-80/67.环境准备.md
    - 68.NumPy的应用-1: Day66-80/68.NumPy的应用-1.md
    - 69.NumPy的应用-2: Day66-80/69.NumPy的应用-2.md
    - 70.NumPy的应用-3: Day66-80/70.NumPy的应用-3.md
    - 71.NumPy的应用-4: Day66-80/71.NumPy的应用-4.md
    - 72.深入浅出pandas-1: Day66-80/72.深入浅出pandas-1.md
    - 73.深入浅出pandas-2: Day66-80/73.深入浅出pandas-2.md
    - 74.深入浅出pandas-3: Day66-80/74.深入浅出pandas-3.md
    - 75.深入浅出pandas-4: Day66-80/75.深入浅出pandas-4.md
    - 76.深入浅出pandas-5: Day66-80/76.深入浅出pandas-5.md
    - 77.深入浅出pandas-6: Day66-80/77.深入浅出pandas-6.md
    - 78.数据可视化-1: Day66-80/78.数据可视化-1.md
    - 79.数据可视化-2: Day66-80/79.数据可视化-2.md
    - 80.数据可视化-3: Day66-80/80.数据可视化-3.md
  - Day81-90:
    - 81.人工智能和机器学习概述: Day81-90/81.人工智能和机器学习概述.md
    - 82.k最近邻分类: Day81-90/82.k最近邻分类.md
    - 83.决策树: Day81-90/83.决策树.md
    - 83.推荐系统实战-1: Day81-90/83.推荐系统实战-1.md
    - 84.贝叶斯分类: Day81-90/84.贝叶斯分类.md
    - 85.支持向量机: Day81-90/85.支持向量机.md
    - 86.K-均值聚类: Day81-90/86.K-均值聚类.md
    - 87.回归分析: Day81-90/87.回归分析.md
    - 88.深度学习入门: Day81-90/88.深度学习入门.md
    - 89.PyTorch概述: Day81-90/89.PyTorch概述.md
    - 90.PyTorch实战: Day81-90/90.PyTorch实战.md
  - Day91-100:
    - 91.团队项目开发的问题和解决方案: Day91-100/91.团队项目开发的问题和解决方案.md
    - 92.Docker容器技术详解: Day91-100/92.Docker容器技术详解.md
    - 93.MySQL性能优化: Day91-100/93.MySQL性能优化.md
    - 94.网络API接口设计: Day91-100/94.网络API接口设计.md
    - 95.使用Django开发商业项目: Day91-100/95.使用Django开发商业项目.md
    - 96.软件测试和自动化测试: Day91-100/96.软件测试和自动化测试.md
    - 97.电商网站技术要点剖析: Day91-100/97.电商网站技术要点剖析.md
    - 98.项目部署上线和性能调优: Day91-100/98.项目部署上线和性能调优.md
    - 99.面试中的公共问题: Day91-100/99.面试中的公共问题.md
    - 100.Python面试题实录: Day91-100/100.Python面试题实录.md